git clone https://github.com/folke/which-key.nvim ~/.config/nvim/pack/plugins/start/which-key.nvim
git clone https://github.com/echasnovski/mini.surround ~/.config/nvim/pack/plugins/start/mini.surround
git clone https://github.com/ibhagwan/fzf-lua ~/.config/nvim/pack/plugins/start/fzf-lua
git clone https://github.com/nvim-treesitter/nvim-treesitter ~/.config/nvim/pack/plugins/start/nvim-treesitter
git clone https://github.com/mg979/vim-visual-multi ~/.config/nvim/pack/plugins/start/vim-visual-multi
git clone https://github.com/lambdalisue/suda.vim ~/.config/nvim/pack/plugins/start/suda.vim
git clone https://github.com/embear/vim-foldsearch ~/.config/nvim/pack/plugins/start/vim-foldsearch
git clone https://github.com/tpope/vim-fugitive ~/.config/nvim/pack/plugins/start/vim-fugitive
git clone https://github.com/ellisonleao/gruvbox.nvim ~/.config/nvim/pack/plugins/start/gruvbox.nvim
